# Generated by Django 4.0.1 on 2022-01-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animals_app.category'),
            preserve_default=False,
        ),
    ]
